require_relative 'function_dictionary'

FunctionDictionary.add(:+, %i[INT INT] => :INT)
FunctionDictionary.add(:-, %i[INT INT] => :INT)
FunctionDictionary.add(:%, %i[INT INT] => :INT)
FunctionDictionary.add(:/, %i[INT INT] => :INT)
FunctionDictionary.add(:*, %i[INT INT] => :INT)
FunctionDictionary.add(:"=", %i[INT INT] => :BOOL)
FunctionDictionary.add(:<=, %i[INT INT] => :BOOL)
FunctionDictionary.add(:<, %i[INT INT] => :BOOL)
FunctionDictionary.add(:>=, %i[INT INT] => :BOOL)
FunctionDictionary.add(:>, %i[INT INT] => :BOOL)
FunctionDictionary.add(:!, %i[BOOL] => :BOOL)
FunctionDictionary.add(:print, %i[STRING] => :INT)
FunctionDictionary.add(:concat, %i[STRING STRING] => :STRING)
