AllCops:
    Exclude:
        - 'spec/spec_helper.rb'

Layout/LineLength:
    Max: 100
Layout/MultilineMethodCallBraceLayout:
    EnforcedStyle: same_line
Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Metric/AbcSize:
    Max: 20
Metric/BlockLength:
    Exclude:
        - '**/*_spec.rb'
Metric/MethodLength:
    Max: 20

Style/FrozenStringLiteralComment:
    Enabled: false
